[package]
name = "hippocampus"
version = "0.0.0"
edition = "2021"
readme = "README.md"
description = "Brain Inspired AI <emory"
license = "MIT/Apache-2.0"
authors = ["b0xtch"]
repository = "https://github.com/b0xtch/hippo"


[dependencies]
